#!/usr/bin/env node
// Solve Rhode Island hold'em (rank deck) with CFR+ and export the quantized
// average strategy for the browser trainer:  node build-rih.js
'use strict';

const fs = require('fs');
const path = require('path');
const { vRIH, VSolver } = require('./vsolver.js');

const TARGET_MA = 1.0; // milli-antes/hand
const MAX_ITERS = 1500;
const CHECK_EVERY = 50;

const s = new VSolver(vRIH());
console.log(`tree: ${s.nodes.length} nodes, ${s.infosetCount} infosets, ${s.entries} strategy entries`);

const t0 = Date.now();
let eps = Infinity;
while (s.iterations < MAX_ITERS) {
  s.train(CHECK_EVERY);
  eps = s.exploitability() * 1000;
  const secs = ((Date.now() - t0) / 1000).toFixed(0);
  console.log(`iter ${s.iterations}  exploitability ${eps.toFixed(4)} mA  value(P1) ${s.gameValue0().toFixed(5)}  [${secs}s]`);
  if (eps < TARGET_MA) break;
}

const q = s.exportQuantized();
const meta = {
  game: 'rih',
  iterations: s.iterations,
  exploitabilityMA: +eps.toFixed(4),
  gameValueP0: +s.gameValue0().toFixed(6),
  entries: q.length,
};
const out =
  '// Precomputed CFR+ average strategy for Rhode Island hold\'em (rank deck).\n' +
  '// Generated by build-rih.js — do not edit.\n' +
  'window.RIH_STRATEGY = {\n' +
  `  meta: ${JSON.stringify(meta)},\n` +
  `  data: "${Buffer.from(q).toString('base64')}"\n` +
  '};\n';
fs.writeFileSync(path.join(__dirname, 'rih-strategy.js'), out);
console.log(`wrote rih-strategy.js (${(out.length / 1e6).toFixed(1)} MB, meta: ${JSON.stringify(meta)})`);
